In [2]:
import numpy as np
list_numbers = [[12, 23, -45], [18, -77, -44]]

Using NumPy, create an array from the list. Write a code to
return all the negative numbers in the list.

In [4]:
# Convert to NumPy array
arr = np.array(list_numbers)

# Boolean indexing to filter negative numbers
negative_numbers = arr[arr < 0]

print("Negative numbers:", negative_numbers)

Negative numbers: [-45 -77 -44]


Using NumPy, write code to multiply each element in the
array you created in question 1 by 2. Create a new variable
for this array.

In [5]:
new_array = np.multiply(arr, 2)
new_array

array([[  24,   46,  -90],
       [  36, -154,  -88]])

 Write code to calculate the sum of the numbers on axis-1 of
the array you created in question 2.

In [6]:
# Calculate sum along axis=1 (row-wise)
row_sum = np.sum(new_array, axis=1)
row_sum

array([ -20, -206])

Write code to calculate the sum of numbers on axis-0 of the
array you created in question 2.

In [7]:
#Calculate sum along axis=0 (column-wise)
row_column = np.sum(new_array, axis=0)
row_column

array([  60, -108, -178])

Using the NumPy arange() function, create a NumPy array
of numbers from 0 to 99. The shape of the array must be
(2, 5, 10).

In [9]:
# Create array of numbers from 0 to 99
arr1 = np.arange(100)
arr1_reshaped = arr1.reshape(2, 5, 10)
arr1_reshaped

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

Write code to slice row [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
from the array above (question 5).

In [10]:
row = arr1_reshaped[1, 0, :]  ## block 1, row 0, all columns (indexing starts at 0)

row

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

Let’s analyze the array you created in question 1 further.
How many numbers in row 1 are greater than the numbers
in row 2?

In [ ]:
# Compare row 1 and row 2 element-wise
comparison = arr[0] > arr[1]
# Count how many True values
count_greater = np.sum(comparison)

print("Row 1 values greater than Row 2:", count_greater)
