Create an array using the list below. Write code to sort the
array in ascending order: first sort by columns, then by
rows. Create a new variable for each of the sorted arrays.

In [2]:
import numpy as np
list1 = [[12, 34, 56], [12, 13, 8,], [6, 5, 10]]
# Create an array
arr = np.array(list1)
print("Origional array created:", arr)
# Sort the array in ascending order
arr_asc_col = np.sort(arr, axis=0)
arr_asc_row = np.sort(arr, axis=1)
# Print each
print("Sorted by column:", arr_asc_col)
print("Sorted by row:", arr_asc_row)

Origional array created: [[12 34 56]
 [12 13  8]
 [ 6  5 10]]
Sorted by column: [[ 6  5  8]
 [12 13 10]
 [12 34 56]]
Sorted by row: [[12 34 56]
 [ 8 12 13]
 [ 5  6 10]]


Using NumPy slicing, write a code that slices these
numbers in this order [8, 12, 56] from the array sorted by
columns (question 1). Create a new variable.  

In [4]:
import numpy as np
# Slice numbers in the order [8, 12, 56]
# The elements are located at (0,2), (1,0), and (2,2) in arr_asc_col
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 2])
sliced_arr = arr_asc_col[row_indices, col_indices]
print("Sliced array:", sliced_arr)

Sliced array: [ 8 12 56]


 Create a 2-dimensional array of random integers between
100 and -100 in the shape (3, 3). Use the np.where()
function to replace all negative values in the array with 0.
Use a seed to save the random numbers generated.

In [7]:
# Create two dimensional array
rng = np.random.default_rng(seed=42)
arr = rng.integers(low=-100, high=100, size=(3, 3))
# Use np.where() function to replace negative values with zero
arr_zero = np.where(arr < 0, 0, arr)
print("Original array:", arr)
print("Array with negative values replaced with zero:", arr_zero)

Original array: [[-83  54  30]
 [-13 -14  71]
 [-83  39 -60]]
Array with negative values replaced with zero: [[ 0 54 30]
 [ 0  0 71]
 [ 0 39  0]]


Create an array from the list below.
Using the np.unique() function, return the unique
elements in the array and the counts of each unique
element (how many times each element appears in
the list).

In [8]:
list1 = [[12, 23, 34, 34], [13, 13, 20, 21]]
array1 = np.array(list1)
# Use np.unique function to return unique elements in the array
unique_elements, counts = np.unique(array1, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts of each unique element:", counts)

Unique elements: [12 13 20 21 23 34]
Counts of each unique element: [1 2 1 1 1 2]


Use the np.flatten() function to flatten the nested array
you created in question 4.

In [9]:
# Flatten the above array
flattened_array = array1.flatten()
print("Flattened array:", flattened_array)


Flattened array: [12 23 34 34 13 13 20 21]
