Create a one-dimensional array with random integers
between 0 and 20. The size of the array is 10. Ensure that
the results are reproducible.

In [1]:
import numpy as np

rng = np.random.default_rng(seed=42)
array1 = rng.integers(21, size=10)
array1

array([ 1, 16, 13,  9,  9, 18,  1, 14,  4,  1])

Using slicing, create a subset array of 3 integers from the
array you created in question 1. The first integer is at index
2, the second integer is at index 4, and the third index is
at index 7.

In [2]:
subset_array = array1[[2, 4, 7]]
print(subset_array)

[13  9 14]


Create a two-dimensional array from the list below. Check the
dimensions and shape of your array.

Using slicing, write a code to access the numbers 3, 8, and
13. Your code should return [3, 8, 13].

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
# Converting the list into a numpy array
array2 = np.array(my_list)
array2

# Use ndim to check number of dimensions
array2.ndim

# check shape
array2.shape

#Use slicing to access the numbers
sub_array = array2[0, 2], array2[1, 2], array2[2, 2]
print(np.array(sub_array))

[ 3  8 13]


 Create a three-dimensional array from the nested list below:

Using slicing, write code that creates a sublist from the
array you created. Your code should return an array of
numbers (4, 8, and 15).

In [4]:
list1 = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]
# Convert nested list into a numpy array
array3 = np.array(list1)

# Slicing to create the sublist
sub_list = array3[0, 0, 3], array3[0, 1, 2], array3[0, 2, 4]
print(np.array(sub_list))

[ 4  8 15]
