 Using the arange() function, create an array of numbers
from 0 and 10. The shape of the array must be (2, 5).

In [1]:
import numpy as np
array = np.arange(0, 10).reshape(2, 5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Write a code to change the shape of the array (question 1)
to (5, 2). Create a new variable for this array. Now, add this
array to the original array in question 1. The resulting array
should have shapes (2, 5). Save this as a variable.

In [4]:
# reshaping the array
array2 = array.reshape(5,2)
array2

# adding array to origional array
array3 = array2.transpose() + array
array3

array([[ 0,  3,  6,  9, 12],
       [ 6,  9, 12, 15, 18]])

Swap the indexes of the array (question 2) using the
swapaxis() method. Create a new variable for the swapped
array.

In [5]:
swapped_array = np.swapaxes(array3, 0, 1)
swapped_array

array([[ 0,  6],
       [ 3,  9],
       [ 6, 12],
       [ 9, 15],
       [12, 18]])

Write a code to slice row 1 from the swapped array in
question 3.

In [7]:
row_one = swapped_array[0, :]
row_one

array([0, 6])